// @ts-check

/**
 * Modern, engaging sidebar for LearnVertexNova
 * - Uses generated index pages for "landing" sections
 * - Uses autogenerated items so you don't maintain lists by hand
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // This name MUST match your navbar sidebarId: 'mainSidebar'
  mainSidebar: [
    // 1) Start Here
    {
      type: 'doc',
      id: 'intro',
      label: 'Start Here',
    },

    // 2) Overview
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'docs/overview',
      },
      items: [
        { type: 'doc', id: 'docs/overview', label: 'Overview' },
        { type: 'doc', id: 'docs/overview-architecture', label: 'Architecture' },
        { type: 'doc', id: 'docs/overview-design', label: 'Design' },
        { type: 'doc', id: 'docs/roadmap', label: 'Roadmap' },
      ],
    },

    // 4) Learn by Building
    {
      type: 'category',
      label: 'Learn by Building',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Learn by Building',
        description:
          'Hands-on chapters. Every concept maps to runnable code.',
        slug: '/learn',
      },
      items: [{ type: 'autogenerated', dirName: 'docs/learn' }],
    },

    // 5) Demos
    {
      type: 'category',
      label: 'Demos',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'docs/demos/index',
      },
      items: [{ type: 'autogenerated', dirName: 'docs/demos' }],
    },

    // 6) Coding Guidelines
    {
      type: 'category',
      label: 'Coding Guidelines',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'coding-guidelines',
          label: 'C++ Guidelines',
        },
        {
          type: 'doc',
          id: 'glsl-coding-guidelines',
          label: 'GLSL Guidelines',
        },
      ],
    },

    // 7) Misc
    {
      type: 'category',
      label: 'Misc',
      collapsed: true,
      items: [
        { type: 'doc', id: 'docs/misc/color-palette', label: 'Color Palette' },
        { type: 'doc', id: 'docs/misc/glossary', label: 'Glossary' },
      ],
    },

    // 8) Guides & Extras
    {
      type: 'category',
      label: 'Guides & Extras',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Guides & Extras',
        description:
          'Tooling, deployment, and workflow tips to stay productive.',
        slug: '/guides',
      },
      items: [{ type: 'autogenerated', dirName: 'tutorial-extras' }],
    },

    // 9) About
    {
      type: 'doc',
      id: 'about',
      label: 'About',
    },
  ],
};

export default sidebars;
